<?php
/** @var $block \Smile\Catalog\Block\Category\ListCategoryProducts */

$categoryId = (int)$this->getRequest()->getParam('id');

$block->getToolbarHtml();
$block->getAdditionalHtml();

$viewMode = $block->getMode() == 'grid' ? 'grid' : 'list';
$imageDisplayArea = $block->getMode() == 'grid' ? 'category_page_grid' : 'category_page_list';
$showDescription = $block->getMode() == 'grid' ? false : true;
$templateType = $block->getMode() == 'grid'
    ? \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW
    : \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$showWishlist = true;
$showCompare = true;
$imageWidth = 150;
$imageHeight = 120;

/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
?>

<div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
    <ol class="products list items product-items" data-bind="scope:'product_list'" id="product-listing">
            <li class="item product product-item" data-bind="foreach: { data: productList, as: 'product' }">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                        if ($pos != null) {
                            $position = ' style="left:' . $imageWidth . 'px;'
                                . 'top:' . $imageHeight . 'px;"';
                        }
                    ?>

                    <a data-bind="attr: {href: product.url}"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <img data-bind="attr: {src: product.src}" alt="Product Image">
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               data-bind="attr: {href: product.url}">
                                <span data-bind="text: product.name"></span>
                            </a>
                        </strong>
                        <div data-bind="html: product.price"></div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <!-- ko if: product.is_saleable == 1 -->
                                        <button type="button"
                                                class="action tocart primary"
                                                data-bind="attr: {'data-post': product.post_data}"
                                                data-role="tocart-form">
                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                        </button>
                                    <!-- /ko -->
                                    <!-- ko if: product.is_saleable == 0 -->
                                        <!-- ko if: product.is_available == 1 -->
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <!-- /ko -->
                                        <!-- ko if: product.is_available == 0 -->
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <!-- /ko -->
                                    <!-- /ko -->
                                </div>
                                <div class="product links" data-role="add-to-links">
                                    <?php if ($showWishlist == true) :?>
                                        <a  href="#"
                                            data-bind="attr: {'data-post': product.add_to_wishlist_params}"
                                            class="action towishlist"
                                            data-action="add-to-wishlist">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')); ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($showCompare == true) :?>
                                        <a href="#"
                                           class="action tocompare"
                                           data-bind="attr: {'data-post': product.add_to_compare_params}"
                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <b data-bind="text: product.short_description"></b>
                                    <a data-bind="attr: {href: product.url, title: product.name}"
                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </li>
    </ol>

    <script type="text/x-magento-init">
    {
        "#product-listing": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "product_list": {
                        "component": "Smile_Catalog/js/view/product/listing",
                        "requestUrl": "<?= $block->getUrl('catalog/category/productListing'); ?>",
                        "categoryId": <?= $categoryId; ?>
                    }
               }
            }
        }
    }
    </script>

    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
    <?php endif; ?>
</div>

